version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imagens
    ports:
      - '5434:5432'
    volumes:
      - ./data-container:/var/lib/postgresql/data
    networks:
      - imagesapinet

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    ports:
      - '15434:80'
    depends_on:
      - db
    networks:
      - imagesapinet

  sbootapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imagesapi
    restart: on-failure
    depends_on:
      - db
    ports:
      - '8080:8080'
    networks:
      - imagesapinet
    environment:
      - "POSTGRES_HOST=db"


networks:
  imagesapinet:
    driver: bridge

